#@ load("@ytt:data", "data")
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: MYPIPELINEAPP
spec:
  serviceAccountName: default
  fetch:
    - git:
        url: #@ "https://github.com/{}/{}".format(data.values.git_repo_user,data.values.git_repo_app)
        ref: #@ "origin/{}".format(data.values.environment_name)
    - http:
        url: #@ "https://api.github.com/repos/{}/{}/commits/{}".format(data.values.git_repo_user, data.values.git_repo_app, data.values.environment_name)

  template:
    - ytt:
        paths:
          - 0/config/cifar/job.yaml
          - 0/config/cifar/pipeline.yaml
          - 0/config/cifar/values.yaml
          - #@ "1/{}".format(data.values.environment_name)

  deploy:
    - kapp: {}